//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "IStudentService")]
public interface IStudentService
{

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/InsertTest", ReplyAction = "http://tempuri.org/IStudentService/InsertTestResponse")]
    long InsertTest();

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IStudentService/GetTest", ReplyAction = "http://tempuri.org/IStudentService/GetTestResponse")]
    Try.Service.Application.Dto.Students.StudentDto[] GetTest();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IStudentServiceChannel : IStudentService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class StudentServiceClient : System.ServiceModel.ClientBase<IStudentService>, IStudentService
{

    public StudentServiceClient()
    {
    }

    public StudentServiceClient(string endpointConfigurationName) :
            base(endpointConfigurationName)
    {
    }

    public StudentServiceClient(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public StudentServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
    {
    }

    public StudentServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
    {
    }

    public long InsertTest()
    {
        return base.Channel.InsertTest();
    }

    public Try.Service.Application.Dto.Students.StudentDto[] GetTest()
    {
        return base.Channel.GetTest();
    }
}
